### PR TITLE
Cohttp

### PR DESCRIPTION
**Pull request by Drup**
Follows and is based on https://github.com/ocsigen/ocsigenserver/pull/63. This one contains the actual cohttp stuff. Starts after the commit https://github.com/ocsigen/ocsigenserver/commit/49f64330ee9afb83216a64cbd909cea973a9a2e3

### CODE REVIEW

**Comment by Drup** [comment]
@dinosaure @rgrinberg It doesn't build, and I don't know cohttp enough to know why, please fix. :3

**Comment by Drup** [comment]
ok, thanks to @rgrinberg, it builds and launches now.

**Comment by rgrinberg** [comment]
This frankenstein actually works O_o?

**Comment by rgrinberg** [comment]
@Drup is your rebase magic great enough to kick out the bytes commits?

**Comment by Drup** [comment]
It launches, as in `make run.local` do answer on `localhost:8080`. I'm not bold enough to say it *works*. ;)

What do you mean for the bytes commit ?
I already separated the bytes commit it two part, one in each PR. The other PR should be merged rather quickly, as it doesn't change any behavior, as far as I can see, just moving stuff in new files.

**Comment by rgrinberg** [comment]
I mean that I'd like to give it another more thorough review but the diff is still a little heavy. I guess there's only so much magic you can do :/

**Comment by Drup** [comment]
Are you looking commit by commit ? Apart from the big cohttp commit, the rest is small. And the big one is almost only the cohttp stuff. I didn't looked closely at the big commit yet.

**Comment by rgrinberg** [comment]
@Drup at this point IMO it's a question of testing. I'm happy to help out but given that you're more experienced you should take the lead and make a plan for us. I'll be happy to help out.

**Comment by dinosaure** [comment]
I found the [original patch](http://paste.isomorphis.me/YmD&ln) of this. The first problem is the exception `Ocsigen_Is_a_directory` is used in `Ocsigen_extensions` (l. 190 of original patch) and in `Ocsigen_server` (l. 290 of original patch) - and in `Ocsigen_local_files`.

The second problem is the type of exception. The old type of `Ocsigen_Is_a_directory` is `Ocsigen_extensions.request`. So, `Ocsigen_server` is dependent with `Ocsigen_extensions` by the exception and by the type of the exception. In this case, it's no possible to extract `Ocsigen_extensions.request` (the type of the exception) from `Ocsigen_extensions`, it's too complicate and there are just a little part of this record whom is used by `Ocsigen_server`. This part is `Ocsigen_extensions.request_info`. So I decided to get off this type in the new module `Ocsigen_request_info` (best module ever) and change the type of `Ocsigen_Is_a_directory` to get off the dependence of `Ocsigen_extensions.request` in `Ocsigen_server`.

Now, `Ocsigen_server` has just need to apply the function of this exception without know `Ocsigen_extensions.request`.

**Comment by rgrinberg** [comment]
@Drup @dinosaure Seems like there's a bug somewhere:

```
$ make run.opt.local
$ curl 'http://localhost:8080/ocsigenstuff/rpm.png'
```

Will not give you an image back.

This is where teh exception is thrown https://github.com/ocsigen/ocsigenserver/blob/c075d52d9fb97a0bdb9858533eea450b8107dddc/src/server/ocsigen_extensions.ml#L922

**Comment by rgrinberg** [comment]
Looks like the above test only fails in cohttp master. 0.15.2 is working fine. We'll need to bisect through this stuff

https://github.com/mirage/ocaml-cohttp/compare/v0.15.2...master

**Comment by dinosaure** [comment]
I found the bug and it's very deep. In mirage:ocaml-cohttp@v0.15.2, the main conversion between `Cohttp.Request` and Ocsigen request in `Ocsigen_generate` receive this url if you go to the root of site web: `http://127.0.0.1:5858/`. But in mirage:ocaml-cohttp@master, this function receive: `//127.0.0.1:5858/`. It's possible to view the diff with a `print_string` on `url` at [this line](https://github.com/ocsigen/ocsigenserver/pull/64/files#diff-cde1a1934ce844e81e558bd932b7a333R148). The variable `url` is the result of composition between `Uri.of_string` and `Request.uri`.

I don't know if we change the compute of Cohttp or Ocsigen for this bug. I think, it's better to change the compute of Ocsigen.

**Comment by rgrinberg** [comment]
@dinosaure good catch. Is this caused by the following re?

https://github.com/ocsigen/ocsigenserver/blob/501c12bcd30209ee88d77deaf48113437d77ef55/src/baselib/ocsigen_lib.ml#L186

It doesn't allow url's to start without a scheme which is wrong.

**Comment by rgrinberg** [comment]
@Drup @dinosaure OK so there's progress. This branch now works in the happy case. There are some differences in behavior for error handling however. For example:

```
$ curl 'http://0.0.0.0:8080/ocsigenstuff/'
# gives 404 on master
# gives the ugly 500 Error: Ocsigen_extensions.Ocsigen_http_error(_)
$ curl 'http://0.0.0.0:8080/index.html/'
# gives 500 on master
# gives the weird Error: Unix.Unix_error(Unix.ENOTDIR, "stat", # "/Users/rgrinberg/reps/ocsigen/ocsigenserver/local/var/www/index.html/") 
```

**Comment by rgrinberg** [comment]
Backtraces:

```
ocsigenserver.opt: main: exception: Ocsigen_extensions.Ocsigen_http_error(_)
ocsigenserver.opt: main: backtrace:
ocsigenserver.opt: main: Raised at file "ocsigen_local_files.ml", line 179, characters 24-44
ocsigenserver.opt: main: Called from file "ocsigen_local_files.ml", line 187, characters 13-70
ocsigenserver.opt: main: Called from file "staticmod.ml", line 116, characters 5-73
ocsigenserver.opt: main: Called from file "staticmod.ml", line 130, characters 13-201
ocsigenserver.opt: main: Called from file "src/core/lwt.ml", line 685, characters 20-24
```

```
ocsigenserver.opt: main: exception: Unix.Unix_error(Unix.ENOTDIR, "stat", "/Users/rgrinberg/reps/ocsigen/ocsigenserver/local/var/www/index.html/")
ocsigenserver.opt: main: backtrace:
ocsigenserver.opt: main: Raised by primitive operation at file "ocsigen_local_files.ml", line 157, characters 15-43
ocsigenserver.opt: main: Called from file "staticmod.ml", line 116, characters 5-73
ocsigenserver.opt: main: Called from file "staticmod.ml", line 130, characters 13-201
ocsigenserver.opt: main: Called from file "src/core/lwt.ml", line 685, characters 20-24
```

**Comment by Drup** [comment]
I'm getting 
```
make: Dépendance circulaire ocsigen_cohttp_server.cmx <- ocsigen_range.cmx abandonnée.
make: Dépendance circulaire ocsigen_generate.cmx <- ocsigen_range.cmx abandonnée.
```
quite often. It's rather annoying in practice.

**Comment by Drup** [comment]
The eliom test runs, I'll paste the differences here:
- in /uasuffix/2007/6
original: The suffix of the url is 2007/6, your user-agent is Mozilla/5.0 (X11; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0, your IP is ::1
cohttp: The suffix of the url is 2007/6, your user-agent is Mozilla/5.0 (X11; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0, your IP is 0.0.0.0

**Comment by Drup** [comment]
The CRSF test is broken on both.

**Comment by Drup** [comment]
alternative parameters seem to be broken too, on both.

**Comment by Drup** [comment]
That's pretty much it. All the other things pass.

**Comment by vouillon** [comment]
I noticed the following issues last month. We need to check that they are properly addressed:
- [ ] `Ocsigen_request_info.get_server_address` is not implemented but is used by the reverse proxy;
- [ ] the functions in the `migrate` directory should not raise `Invalid_argument` exceptions (more generally, a bogus HTTP client should not be able to trigger this kind of exception);
- [ ] the `Ocsigen_http_error` exception carries a set of cookies to be sent back to the HTTP client, but these cookies are currently ignored;
- [ ] we should probably remove the `awake` functions in `Ocsigen_extensions`.

**Comment by dinosaure** [comment]
Thanks @vouillon for review and rebase, I'll work in your issues this Friday :+1:. And specificaly for `awake`, I agree with you and it will be a ease for #52.

**Comment by dinosaure** [comment]
The first issue of @vouillon is fixed by [this branch](https://github.com/ocsigen/ocsigenserver/tree/fix_get_server_address).

**Comment by vouillon** [comment]
What happened to `Ocsigen_server.handle_result_frame`, which checks whether the requested resource has been modified?

**Comment by jpdeplaix** [comment]
Note that it doesn't compile with cohttp 0.17.
Also, don't forget to remove ppx_deriving before merging this (or add it in the opam file)

**Comment by rgrinberg** [comment]
@jpdeplaix it now compiles

**Comment by jpdeplaix** [comment]
Mmmh I think the opam file still needs to be updated with cohttp >= 0.17.0 instead of >= 0.16.0 and by adding ppx_deriving. But thanks anyways :)

**Comment by rgrinberg** [comment]
Ah yes, thanks for reminding. ppx_deriving will go away once we finish debugging

**Comment by Drup** [comment]
CI is fixed now. We will still remove ppx_deriving before merging (there is just one isolated commit to drop).

**Comment by rgrinberg** [comment]
@dinosaure Why did you implement cookie serialization from scratch? (`To_cohttp.Cookie`) Shouldn't there be some ocsigen utility to write the header for you?

**Comment by rgrinberg** [comment]
@vouillon I don't think those exceptions can crash the server (they get turned into 500's in the catch all) but they can certainly be handled better.

**Comment by dinosaure** [comment]
@rgrinberg It's still a compatibility story. The Ocsigen_cookie module is a distinct library used by Eliom - this is why I think that this module is quite poor. We can not change the type of Ocsigen.Cookie without breaking compatibility with Eliom. Type of Cohttp Cookie is a list whereas it is a map in Ocsigen.

This required a heavy To_cohttp.Cookie.serialize converter to switch from one type to another. Note, this is the biggest runtime conversion - there are also conversions between polymorphic variants and variants (for HTTP method for example).

**Comment by rgrinberg** [comment]
@dinosaure I understand that, I'm just looking for ocsigenserver's original cookie parsing/writing code. I was wondering if that could somehow be co-opted. But it seems like that's exactly what you've done rather than reinventing yourself.

Also, I've addressed a few of @vouillon's points in #76, #77, #78. Could you give them a glance if you have some time? You know this migration better than anyone.

**Comment by Drup** [comment]
@dinosaure I pushed your (modified) stuff. I'm not very happy about the remaining assert false.

**Comment by dinosaure** [comment]
@Drup fix assert with ocsigen@d851d6f.

**Comment by Drup** [comment]
@dinosaure Ok, I like this version much better. It's quite nice now.

**Comment by Drup** [comment]
aaand I killed awake.

**Comment by Drup** [comment]
I pushed 3 bug fixes. You can thanks warning 27.

**Comment by vouillon** [comment]
HTTP/1.0 seems to be broken:
```
$ telnet localhost 8080
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.0

HTTP/1.1 400 Bad Request
content-length: 43

Error: Ocsigen_lib_base.Ocsigen_Bad_Request
Connection closed by foreign host.
```

**Comment by vouillon** [comment]
There is no buffering, so the reply can be extremely fragmented. But that's probably more an issue with Eliom/Tyxml than with Ocsigenserver.
```
6
<input
19
 placeholder="Your email"
10
 name="username"
d
 type="email"
3
 />
```

**Comment by mfp** [comment]
While doing some benchmarks, I ran into this:

https://github.com/ocsigen/ocsigenserver/pull/64/files#diff-af00eddd5261fa6f6ab200223ead43f5R137

The `Lwt_log.ign_debug_f` is not removed/rewritten by `pa_lwt_log`, so the pretty printing (with Format!) is performed on every request. Merely changing to `ignore begin ... Lwt_log.debug_f ...` does not work even though the `lwt.syntax.log` is used because `-syntax camlp4o` isn't (maybe to prevent some ppx incompatibility).

Commenting it gives over 30% speedup in smaller responses.

With this, the buffer pool in conduit, the last-chunk optimization and a change in the buffer size used by `Ocsigen_senders.File_content`, I've got cohttp_rebased within 5% of 2.6 with `Lwt_chan` fix + buffer pool + last-chunk opt (actually a bit faster at small responses, about the same speed in very large ones).

**Comment by Drup** [comment]
Except for the debug printer I hacked quickly (46fcee6), we are not using ppx so we should be able to enable camlp4. Thanks you for the pointer.

**Comment by vasilisp** [comment]
Closing. We have revived the Cohttp effort in another branch. PR to come .

**Pull request closed without merging**
