### PR TITLE
Add GitHub Actions workflow

### PR DESCRIPTION
**Pull request by smorimoto**
We use the Option module, so we need to bump the minimum version requirement.

### CODE REVIEW

**Comment by jrochel** [comment]
I don't know anything about GitHub Actions but I'm inclined to simply merge this PR and see how things go. @balat @vouillon ?

**Comment by balat** [comment]
Yes

**Comment by jrochel** [comment]
Thanks.

**Comment by jrochel** [comment]
@smorimoto H there. Have you noticed the failed test on https://github.com/ocsigen/ocsigenserver/actions/runs/784813399? Do you know of any solution?

**Comment by smorimoto** [comment]
We may need to add this package to the dependencies or just install in the CI workflow.
https://opam.ocaml.org/packages/conf-dbm/

**Comment by jrochel** [comment]
I don't see how adding conf-dbm to the dependencies would improve things. It is actually during the compilation of conf-dbm that the error occurs.

I guess someone needs to update conf-dbm to install `gdbm.h` on ubuntu 4.12.x. I'll look into that.

**Comment by jrochel** [comment]
Ehm, I meant on Ubuntu with Ocaml 4.12.x, obviously.

**Comment by smorimoto** [comment]
Oh indeed, let me check that.

**Comment by jrochel** [comment]
https://github.com/ocaml/opam-repository/issues/18581

**Comment by jrochel** [comment]
Apparently this is an opam issue: https://github.com/ocaml/opam-repository/issues/18581

**Pull request merged**
