### PR TITLE
Much more efficient implementation of Ocsigen_lib.Url.encode

### LINKED ISSUE #117: Ocsigen_lib.Url.encode is slow
`Ocsigen_lib.Url.encode` is not implemented in a very efficient way: slow and too many memory allocations.

This can be an issue in Eliom as we are using it to encode the OCaml values that we send to the client during an RPC.

### PR DESCRIPTION
**Pull request by vouillon**
Faster, and perform much less memory allocations.
Fixes #117.

### CODE REVIEW

**Comment by Drup** [comment]
Not to be disrespectful to your artistic work ... but can't we use `uri` for that ?

**Comment by vouillon** [comment]
`uri` does not provide an implementation of `encode ~plus:true`. But I guess it is safe to encode a space as `%20` instead of `+`.

Also, this is not the most efficient way to escape characters...
```ocaml
Buffer.add_string buf (Printf.sprintf "%%%02X" c);
```

Shall we improve `uri` instead?

**Comment by Drup** [comment]
> Shall we improve uri instead?

Yes!

**Comment by vasilisp** [comment]
`cohttp` uses `uri` extensively, so we had better switch to `uri` everywhere during the `cohttp` transition (which I am working on).

But of course we can merge and use this for now.

**Comment by dinosaure** [comment]
@vasilisp if you want any help, I have some codes to try to switch to `uri` (but it's not done, I have no time) and I know the code of `ocsigenserver`. You can contact me on IRC with the same username or by email 👍 .

**Comment by vasilisp** [comment]
@dinosaure thanks, I really appreciate it! I am building on your work (with @rgrinberg @Drup) for `cohttp` (see the `cohttp_revived` branch if curious), and I think the `uri` migration will happen in parallel with that. I will contact you as needed.

**Pull request merged**
